# Skal have lavet NodeJS service 
# Mangler struktur i fil hierarkiet (volumes).
# Free Radius er ikke testet
# Sikre at depends_on: er opsat der hvor det skal bruges.

version: "3.9"

services:
  
  proxy:
    container_name: proxy
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      #- "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ./data/nginx:/data
      - ./data/certs/letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/npm.sqlite"
    networks:
      - app
    restart: unless-stopped
  
  frontend:
    container_name: frontend
    image: httpd
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/local/apache2/htdocs
    depends_on:
      - proxy
    restart: unless-stopped
  
  backend:
    container_name: backend
    image: node:16.10.0-buster
    ports:
      - "8880:80"
    volumes:
      - ./backend:/app
      - /app/node_modules # Mads486m: For at undgå kopiering af node modules til container context, da det vil gøre den sløv
    depends_on:
      - proxy
    restart: unless-stopped
    working_dir: /app
    command: npm i; node app.js
  
  mariadb:
    container_name: mariadb
    image: mariadb
    # ports:
    #   - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      # - ./data/mariadb/radius.sql:/docker-entrypoint-initdb.d/radius.sql
    environment:
      - MYSQL_ROOT_PASSWORD=radius
      - MYSQL_PASSWORD=radpass
      - MYSQL_USER=radius
      - MYSQL_DATABASE=radius
    networks:
      - app
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    networks:
      - app
    restart: unless-stopped

  freeradius:
    container_name: freeradius
    image: "freeradius/freeradius-server:latest"
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    command: -X
    volumes:
       - "./data/freeradius:/data"
    environment:
      - DB_NAME=radius
      - DB_HOST=mariadb
      - DB_USER=radius
      - DB_PASS=radpass
      - DB_PORT=3306
      - DEFAULT_CLIENT_SECRET=testing123
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge