version: "3.9"

services:
  
  proxy:
    container_name: "nginx-proxy"
    #image: jwilder/nginx-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ./config/nginx:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - app
    restart: always
  
  webserver:
    container_name: "apache-webserver"
    image: httpd
    ports:
      - "8080:8080"
    hostname: web
    volumes:
      - "./data/apache/www/html:/var/www/html"
    networks:
       app:    
          aliases:
            - web
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    container_name: "mariadb-db"
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=radius
      - MYSQL_PASSWORD=radpass
      - MYSQL_USER=radius
      - MYSQL_DATABASE=radius
    networks:
      - app
    restart: always

  portainer:
    container_name: "portainer"
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app
    restart: always

networks:
  app:
    driver: bridge

volumes:
  portainer_data: