version: "3.9"

services:
  
  proxy:
    container_name: "nginx-proxy"
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "80:80"
      - "443:443"
      - "81:81"

    volumes:
      #- "/var/run/docker.sock:/tmp/docker.sock:ro"
      #- ./config/nginx:/config
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      #- /tmp/acme_challenge:/tmp/

    environment:
      DB_SQLITE_FILE: "/data/npm.sqlite"

    networks:
      - app
    restart: always
  
  webserver:
    container_name: "apache-webserver"
    image: httpd
    ports:
      - "8080:80"
    hostname: web
    volumes:
      - "./website:/usr/local/apache2/htdocs"
    networks:
       app:    
          aliases:
            - web
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    container_name: "mariadb-db"
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "./data/mariadb:/var/lib/mysql"
      - "./data/mariadb/radius.sql:/docker-entrypoint-initdb.d/radius.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=radius
      - MYSQL_PASSWORD=radpass
      - MYSQL_USER=radius
      - MYSQL_DATABASE=radius
    networks:
      - app
    restart: always

  portainer:
    container_name: "portainer"
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app
    restart: always

  freeradius:
    container_name: "freeradius"
    image: "freeradius/freeradius-server:latest"
    #image: "2stacks/freeradius"
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
       - "./configs/radius/freeradius/:/etc/freeradius/"
       - "./data:/data"
      #- "./configs/radius/users:/etc/raddb/users"
      #- "./configs/radius/clients.conf:/etc/raddb/clients.conf"
    environment:
      #- DB_NAME=radius
      - DB_HOST=mariadb
      #- DB_USER=radius
      #- DB_PASS=radpass
      #- DB_PORT=3306
      #- RADIUS_KEY=testing123
      #- RAD_CLIENTS=172.25.0.0/16
      - RAD_DEBUG=yes
    depends_on:
      - mariadb
    links:
      - mariadb
    restart: always
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  portainer_data:
  data:
  configs:


