version: "3.9"

services:
  
  proxy:
    container_name: "nginx-proxy"
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./config/nginx:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - app
    restart: always
  
  webserver:
    container_name: "apache-service"
    image: httpd
    ports:
      - "80:80"
    networks:
      - app
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=radius
      - MYSQL_PASSWORD=radpass
      - MYSQL_USER=radius
      - MYSQL_DATABASE=radius
    networks:
      - app
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer
    networks:
      - app
    restart: always

networks:
  app:
    driver: bridge