version: "3.3"

services:
  
  nginx:
    container_name: "nginx-service"
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - app
    restart: always
  
  web:
    container_name: "apache-service"
    image: httpd
    ports:
      - "80:80"

networks:
  app:
    driver: bridge